### ISSUE TITLE
Bricked device with firmware update

### ISSUE THREAD

**Issue by pff729** [KimJorgensen/KungFuFlash#104]
I successfully bricked my KungFuFlash. 
I tried to update the firmware from 1.23 to 1.27 (both PAL versions). I've updated the firmware before and it went flawlessly: finished in a couple of seconds. But now, I've connected my KungFuFlash to my C64, opened the update file from the microSD, it wrote "updating in progress" to the screen but then nothing happened. I waited 45 minutes, still nothing, so I powered it off. Now, if I plug it into my C64, there is no sign of life: the screen is black and flickering. 
I'm not sure what caused this. The difference between versions was too big?
Can it be fixed somehow? Maybe writing a firmware on it through the usb port? Or desoldering and swapping some parts? Or is it bricked forever?

**Comment by KimJorgensen** [comment]
Interesting. Now I’m pretty sure that the issue is caused by the changes to the detection of C64 clock signal. If the clock frequency is just outside the accepted range then the KFF will refuse to start but the LED would not blink rapidly.

Here is a new test firmware where two changes has been made:
1. The LED would always blink rapidly if the KFF refuses to start due the C64 clock frequency being out of range
2. The accepted frequency range has been extended a bit

@mofjel Could you try with this new firmware and  report back? Regardless if it works or not, it would be useful to know what frequency you got in the diagnostic tool (pressing the menu button for 2 seconds using v1.27 or the new firmware if it works)

[KungFuFlash_vTST4.zip](https://github.com/KimJorgensen/KungFuFlash/files/7446229/KungFuFlash_vTST4.zip)

**Comment by mofjel** [comment]
I have tested the test firmware, and it works!
So I played around with it, using the final cartridge 3 and action replay 6. Ran some games and demos. Everything works as they should as far as I know. And special button as well. 
Ran som cartridge games, and they also worked as they should.

I tried the 2 sec menu button press. The frequency did vary a bit for each time I used it. 
Highest frequency was 985216Hz
Lowest frequency was 985190Hz
(I did it 3 times)

I did the update using my C64.
I can't find any issues with it using the test firmware, it just works.
I will play around with it some more, and if I notice something, I will report back. 
But it's looking good.

**Comment by KimJorgensen** [comment]
@mofjel That is good news, thanks for testing.
It seems that the issue was caused by a slightly unstable clock frequency in your C64 and a too restrictive frequency check in the KFF firmware.

If you think it is fun to do experiments, you could try to adjust the frequency closer to 985248 Hz and see if the frequency gets more stable. You would do that with R27 next to the VIC-II chip on a 250407 board.
Just note that the KFF is not a precision instrument, so the frequency reading is not 100% accurate, and if you get the frequency wrong you may lose color on your monitor.

I'll create a new v1.29 firmware release with the changes from vTST4.

**Comment by KimJorgensen** [comment]
A [new firmware](https://github.com/KimJorgensen/KungFuFlash/releases/tag/v1.29) has been release that fixes the problem reported by @mofjel 

@pff729 I'm not sure if the issue you reported with v1.27 is related to the clock frequency detection. But if it is, and you have access to another C64 then you could try your bricked KFF with that.

**Comment by pff729** [comment]
Thanks everyone for the help, I'm currently waiting for my ST-Link V2 programmer to arrive and hopefully I can unbrick my device as well.

**Comment by mofjel** [comment]
@KimJorgensen I just want to thank you for taking the time and effort to solve this. And also, it was very fun to participate in this. And if you need help to test anything at a later time, just let me know. I will do it. 
I have tweaked the frequency some, so it is closer to 985248 Hz. 

@pff729 If you want to try the USB method, I have made a little step by step guide how to do this [here](https://everythingc64.boards.net/thread/1326/kung-fu-flash-usb-flashing)
All the information about how to do it, is out there. But I found it a bit hard to piece it all together. So I just wrote it down so maybe it can help someone.

**Comment by Sebby75** [comment]
@mofjel 
> I have made a little step by step guide how to do this 

Thanks for this... Saved your guide and all tools needed to my KFF microsd card just in case, hopefully I will never need it.

Regards
Sebby75

**Comment by pff729** [comment]
Thanks everyone for your help! I managed to unbrick my device with the USB method, installed version 1.32, it works flawlessly. Thanks @mofjel for your detailed guide for the usb method, it is really handy!

**Comment by csico81** [comment]
> @KimJorgensen I just want to thank you for taking the time and effort to solve this. And also, it was very fun to participate in this. And if you need help to test anything at a later time, just let me know. I will do it. I have tweaked the frequency some, so it is closer to 985248 Hz.
> 
> @pff729 If you want to try the USB method, I have made a little step by step guide how to do this [here](https://everythingc64.boards.net/thread/1326/kung-fu-flash-usb-flashing) All the information about how to do it, is out there. But I found it a bit hard to piece it all together. So I just wrote it down so maybe it can help someone.

Hi @mofjel 
Do you still have your guide somehwere? The link does not work anymore. I am facing a similar issue that you had with the Kung Fu flash cartridge. I would take a look at your guide if is possible.
Thank you in advance,
csico

**Comment by Shadowtrance** [comment]
> Hi @mofjel Do you still have your guide somehwere? The link does not work anymore. I am facing a similar issue that you had with the Kung Fu flash cartridge. I would take a look at your guide if is possible. Thank you in advance, csico

Salvaged via wayback machine (and corrected so links actually go somewhere).

------
1. Bridge the connection on J1 (+5v and USB) and bridge BOOTO and +3.3v on J4. Use a jumper to bridge this, because you need a way to remove the bridge after you are done. But you could solder in a jumper lead if you want.

2. Download DFU-UTIL http://dfu-util.sourceforge.net/releases/. It is called dfu-util-0.11.tar.gz. 

3. You need to uncompress it twice using winzip. You should get a folder called dfu-util-0.11-binaries. You could rename the folder to something easier like DFU or something. Copy the folder to somewhere easy to find it. Like i.e C: or the root of some other HDD. Also copy the version of KungFuFlash firmware you want, into the Win64 or Win32 folder inside the DFU folder. 

4. Go to Zadig https://zadig.akeo.ie/ and download the software there. Run it, and it will install the proper USB drivers for this to work. (At least it did for me) You might have to plug in the KungFuFlash for this.

5. Press WIN+R and type cmd in the window. Press enter and the command prompt should pop up.

6. Navigate to the DFU folder i.e: cd C:/dfu.

7. Navigate to the win64 or win32 folder.

8. Connect the KungFuFlash to the USB. 

9. Type in the command prompt window: dfu-util -l  This command will list the compatible dfu devices connected. It found it? Good, now its ready to be flashed.

10. KimJorgensen has kindly typed in the command for flashing firmware, using dfu on his Github page https://github.com/KimJorgensen/KungFuFlash/blob/master/firmware/README.md. You can copy paste it into command prompt, but have to change to the correct firmware name.
      ie: dfu-util -a 0 -s 0x08000000 -D KungFuFlash_v1.29_PAL.upd and press enter.
     
      The KungFuFlash should now be flashed.

11. When dfu-util has done it's job, you disconnect the USB and remove the two jumpers. And it will be ready for use.

**Comment by csico81** [comment]
@Shadowtrance Thank you so much! I will give it a try once I get home. ;)
