### ISSUE TITLE
Use Soft-CPU or small FPGA for KungFu enhancement to black belt..

### ISSUE THREAD

**Issue by mwedmark** [KimJorgensen/KungFuFlash#43]
I'm about to build myself (and some others) a couple of KungfuFlash Carts and are planning to try out everything! Such a cool cart and thanks for making it open-source! I own a C64 Breadbox that I've had for almost 40 years.

I saw that for example the Kernal support was hard to implement due to timing. Have you though about going down the Soft-CPU path or just keep it like today but add small/cheap FPGA? Would there be any major problems with going for a F32C/Microblaze/NIOS(Other 32-bit (100Mhz) CPU and also use some external logic to help out.

Or maybe some of those chinese FPGA circuits, if the bug ones (Xilinx & Altera) is too costly. Would be able to use same exisiting JTAG for programming , either programmed from your current MCU or directly via micro-SD card or Flash. I've been doing hobby FPGA development for 10 years+ and also programming C#/C/C++/assembler both as a profession and for fun.

**Comment by KimJorgensen** [comment]
Thank you.

My design goal was make a cartridge with a feature set like the EasyFlash 3 while keeping the hardware design as simple and cheap as possible.

I did consider many different designs including using a microcontroller with programmable logic or a FPGA. However, due to the different constraints like 5V tolerant logic and the ability to emulate 1MB of flash memory, they all required more components and/or was more expensive.
Not being a hardware designer it could be that it is possible to make a FPGA based design that fits the bill. If you have any specific ideas to this I would be happy to hear them.

It is a weakness of the current design that it is hard to implement timing critical features and using a FPGA would definitely help. However, I would need to spend more time investigating before saying that kernal support is not possible with the current hardware.
